num_episodes: 2
<<<<<<< HEAD
episode_limit: 300
gamma: 0.99
=======
episode_limit: 10000
gamma: 0.9
>>>>>>> main
val_freq: 1
epsilon_start: 1.0

batch_size: 32
tau: 0.01
replay_memory_capacity: 500000
prefill_memory: True